version: '2.4'

services:
  react_native_app:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./MONGO:/opt/MONGO/app:delegated
      - ./MONGO/package.json:/opt/MONGO/package.json
      - ./MONGO/package-lock.json:/opt/MONGO/package-lock.json
      - notused:/opt/MONGO/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused: